#define PIN_BUZZER 12

#define PIN_PWM_BLANK 18
#define PIN_PWM_SCLK 19
#define PIN_PWM_LATCH 22
#define PIN_PWM_SIN 21
#define PIN_PWM_GSCLK 23

#define PIN_I2C_SDA 14
#define PIN_I2C_SCL 27

#define PIN_MAINVOLTS 4

#define PIN_AMP_M1 ADC1_CHANNEL_4
#define PIN_AMP_M2 ADC1_CHANNEL_5
#define PIN_AMP_M3 ADC1_CHANNEL_6
#define PIN_AMP_M4 ADC1_CHANNEL_7
#define PIN_AMP_5V ADC2_CHANNEL_4



